import sys

# SpecificSkillType enum (index -> name)
specific_skill_type = {
    0: "None",
    1: "HealthRegen",
    2: "CriticalStrike",
    3: "LifeSteal",
    4: "MovementSpeed",
    5: "AttackSpeed",
    6: "AreaDamage",
    7: "Projectile",
    8: "Shield",
    9: "Heal",
    10: "DamageReflection",
    11: "ElementalMastery",
    12: "ChainLightning",
    13: "PoisonCloud",
    14: "FireAura",
    15: "IceBarrier",
    16: "WindDash",
    17: "EarthStomp",
    18: "Ultimate",
    19: "Boomerang",
    20: "EscudoRotativo",
    21: "EscudoEspinhoso",
    22: "Aureola",
    23: "BarreiraReflexiva",
    24: "CampoEspinhos",
    25: "ChuvaEstrelas",
    26: "GarrasAbismo",
    27: "FuriaLaminas",
    28: "SombrasCruz",
    29: "CorteFantasma",
    30: "LancaLuz",
    31: "ChicoteEnergia",
    32: "MisseisTeleguiados",
    33: "PulsoRitmico",
    34: "EspadaFantasma",
    35: "CorrenteSombria",
    36: "SegundaChance",
    37: "FugaSombras",
    38: "BarreiraEnergia",
    39: "TeiaProtecao",
    40: "InstintoSobrevivencia",
    41: "EspelhoMagico",
    42: "EscudoKarma",
    43: "UltRaioCerteiro",
    44: "UltTempestadeEletrica",
    45: "UltChuvaMeteorosUlt",
    46: "UltCampoDeGelo",
    47: "UltVortice",
    48: "UltNecropole",
    49: "UltRitualAnciao",
    50: "UltBencaoAnciao",
    51: "UltCasuloCristal",
    52: "UltCorrentesInferno",
    53: "UltDrenagemDeVida",
    54: "UltEscudoSonico",
    55: "UltFormaBestial",
    56: "UltPulsoMagnetico",
    57: "UltPunicaoDivina",
    58: "UltDomoRetardante",
    59: "UltDespertarAnciao",
    60: "CristaisGelo",
}

sst_rev = {v: k for k, v in specific_skill_type.items()}

# SkillEvolutionType enum (index -> name)
skill_evolution_type = {
    0: "Nenhuma",
    1: "EspinhosVenenosos",
    2: "CampoAmpliado",
    3: "ChuvaIntensa",
    4: "ImpactoSismico",
    5: "GarrasVenenosas",
    6: "Execucao",
    7: "LaminasDuplas",
    8: "LaminasExplosivas",
    9: "CruzDupla",
    10: "SombrasPerfurantes",
    11: "CorteTriple",
    12: "CorteLetal",
    13: "LancaPerfurante",
    14: "LancaExplosiva",
    15: "ChicoteEletrico",
    16: "DuplaRotacao",
    17: "SalvaMisseis",
    18: "MisseisExplosivos",
    19: "PulsoIntenso",
    20: "PulsoCadeia",
    21: "EspadaDuplaFantasma",
    22: "EspadaFlamejante",
    23: "CorrenteReforcada",
    24: "CorrenteParalisante",
    25: "EspadaOrbitalDupla",
    26: "EspadaSonica",
    27: "SpiritBallDupla",
    28: "SpiritBallExplosiva",
    29: "EspiralDupla",
    30: "EspiralFuracao",
    31: "HomingMultiplo",
    32: "HomingEterno",
    33: "GarrasAlcance",
    34: "ChicoteAlcance",
    35: "PulsoAlcance",
    36: "EspadaAlcance",
    37: "CorrenteAlcance",
    38: "LancasMultiplas",
    39: "SegundaChanceCura",
    40: "SegundaChanceInvencivel",
    41: "FugaInvulneravel",
    42: "FugaCura",
    43: "BarreiraFortificada",
    44: "BarreiraExplosiva",
    45: "TeiaVenenosa",
    46: "TeiaPermanente",
    47: "InstintoFurioso",
    48: "InstintoEspirito",
    49: "EspelhoAmplificado",
    50: "EspelhoExplosivo",
    51: "KarmaReforcado",
    52: "KarmaRetribuicao",
    53: "EspinhosVenenosos2",
    54: "EspinhosExplosivos",
    55: "AureolaFortificada",
    56: "AureolaExpansiva",
    57: "BarreiraTotal",
    58: "BarreiraCongelante",
    59: "CristaisDuplos",
    60: "CristaisExplosivos",
    61: "RaioEterno",
    62: "RaioOvercarga",
    63: "TempestadeIntensa",
    64: "TempestadeContinua",
    65: "MeteorosDuploImpacto",
    66: "MeteorosMaior",
    67: "GeloAbsoluto",
    68: "GeloEterno",
    69: "VorticeDestruidor",
    70: "VorticeExpansivo",
    71: "NecropoleExercito",
    72: "NecropoleContaminacao",
    73: "RitualAmpliado",
    74: "RitualExplosivo",
    75: "BencaoIntensa",
    76: "BencaoRapida",
    77: "CasuloReforjado",
    78: "CasuloLetal",
    79: "InfernoPropagado",
    80: "InfernoIntensidade",
    81: "DrenagemTotal",
    82: "DrenagemMassiva",
    83: "SonicoAmplificado",
    84: "SonicoPercussao",
    85: "BestialFrenesi",
    86: "BestialRugidoMortal",
    87: "MagneticoSupercarregado",
    88: "MagneticoCentro",
    89: "PunicaoJulgamento",
    90: "PunicaoDivina2",
    91: "DomoFortificado",
    92: "DomoInversor",
    93: "DespertarFurioso",
    94: "DespertarGigante",
}

set_rev = {v: k for k, v in skill_evolution_type.items()}

# Expected values from CriarEvolucoes.cs
expected = {
    "EspinhosVenenosos":       ("CampoEspinhos",           "EspinhosVenenosos"),
    "CampoAmpliado":           ("CampoEspinhos",           "CampoAmpliado"),
    "ChuvaIntensa":            ("ChuvaEstrelas",           "ChuvaIntensa"),
    "ImpactoSismico":          ("ChuvaEstrelas",           "ImpactoSismico"),
    "GarrasVenenosas":         ("GarrasAbismo",            "GarrasVenenosas"),
    "Execucao":                ("GarrasAbismo",            "Execucao"),
    "LaminasDuplas":           ("FuriaLaminas",            "LaminasDuplas"),
    "LaminasExplosivas":       ("FuriaLaminas",            "LaminasExplosivas"),
    "CruzDupla":               ("SombrasCruz",             "CruzDupla"),
    "SombrasPerfurantes":      ("SombrasCruz",             "SombrasPerfurantes"),
    "CorteTriple":             ("CorteFantasma",           "CorteTriple"),
    "CorteLetal":              ("CorteFantasma",           "CorteLetal"),
    "LancaPerfurante":         ("LancaLuz",                "LancaPerfurante"),
    "LancaExplosiva":          ("LancaLuz",                "LancaExplosiva"),
    "ChicoteEletrico":         ("ChicoteEnergia",          "ChicoteEletrico"),
    "DuplaRotacao":            ("ChicoteEnergia",          "DuplaRotacao"),
    "SalvaMisseis":            ("MisseisTeleguiados",      "SalvaMisseis"),
    "MisseisExplosivos":       ("MisseisTeleguiados",      "MisseisExplosivos"),
    "PulsoIntenso":            ("PulsoRitmico",            "PulsoIntenso"),
    "PulsoCadeia":             ("PulsoRitmico",            "PulsoCadeia"),
    "EspadaDuplaFantasma":     ("EspadaFantasma",          "EspadaDuplaFantasma"),
    "EspadaFlamejante":        ("EspadaFantasma",          "EspadaFlamejante"),
    "CorrenteReforcada":       ("CorrenteSombria",         "CorrenteReforcada"),
    "CorrenteParalisante":     ("CorrenteSombria",         "CorrenteParalisante"),
    "GarrasAlcance":           ("GarrasAbismo",            "GarrasAlcance"),
    "ChicoteAlcance":          ("ChicoteEnergia",          "ChicoteAlcance"),
    "PulsoAlcance":            ("PulsoRitmico",            "PulsoAlcance"),
    "EspadaAlcance":           ("EspadaFantasma",          "EspadaAlcance"),
    "CorrenteAlcance":         ("CorrenteSombria",         "CorrenteAlcance"),
    "LancasMultiplas":         ("LancaLuz",                "LancasMultiplas"),
    "SegundaChanceCura":       ("SegundaChance",           "SegundaChanceCura"),
    "SegundaChanceInvencivel": ("SegundaChance",           "SegundaChanceInvencivel"),
    "FugaInvulneravel":        ("FugaSombras",             "FugaInvulneravel"),
    "FugaCura":                ("FugaSombras",             "FugaCura"),
    "BarreiraFortificada":     ("BarreiraEnergia",         "BarreiraFortificada"),
    "BarreiraExplosiva":       ("BarreiraEnergia",         "BarreiraExplosiva"),
    "TeiaVenenosa":            ("TeiaProtecao",            "TeiaVenenosa"),
    "TeiaPermanente":          ("TeiaProtecao",            "TeiaPermanente"),
    "InstintoFurioso":         ("InstintoSobrevivencia",   "InstintoFurioso"),
    "InstintoEspirito":        ("InstintoSobrevivencia",   "InstintoEspirito"),
    "EspelhoAmplificado":      ("EspelhoMagico",           "EspelhoAmplificado"),
    "EspelhoExplosivo":        ("EspelhoMagico",           "EspelhoExplosivo"),
    "KarmaReforcado":          ("EscudoKarma",             "KarmaReforcado"),
    "KarmaRetribuicao":        ("EscudoKarma",             "KarmaRetribuicao"),
    "EspinhosVenenosos2":      ("EscudoEspinhoso",         "EspinhosVenenosos2"),
    "EspinhosExplosivos":      ("EscudoEspinhoso",         "EspinhosExplosivos"),
    "AureolaFortificada":      ("Aureola",                 "AureolaFortificada"),
    "AureolaExpansiva":        ("Aureola",                 "AureolaExpansiva"),
    "BarreiraTotal":           ("BarreiraReflexiva",       "BarreiraTotal"),
    "BarreiraCongelante":      ("BarreiraReflexiva",       "BarreiraCongelante"),
    "CristaisDuplos":          ("CristaisGelo",            "CristaisDuplos"),
    "CristaisExplosivos":      ("CristaisGelo",            "CristaisExplosivos"),
    "RaioEterno":              ("UltRaioCerteiro",         "RaioEterno"),
    "RaioOvercarga":           ("UltRaioCerteiro",         "RaioOvercarga"),
    "TempestadeIntensa":       ("UltTempestadeEletrica",   "TempestadeIntensa"),
    "TempestadeContinua":      ("UltTempestadeEletrica",   "TempestadeContinua"),
    "MeteorosDuploImpacto":    ("UltChuvaMeteorosUlt",     "MeteorosDuploImpacto"),
    "MeteorosMaior":           ("UltChuvaMeteorosUlt",     "MeteorosMaior"),
    "GeloAbsoluto":            ("UltCampoDeGelo",          "GeloAbsoluto"),
    "GeloEterno":              ("UltCampoDeGelo",          "GeloEterno"),
    "VorticeDestruidor":       ("UltVortice",              "VorticeDestruidor"),
    "VorticeExpansivo":        ("UltVortice",              "VorticeExpansivo"),
    "NecropoleExercito":       ("UltNecropole",            "NecropoleExercito"),
    "NecropoleContaminacao":   ("UltNecropole",            "NecropoleContaminacao"),
    "RitualAmpliado":          ("UltRitualAnciao",         "RitualAmpliado"),
    "RitualExplosivo":         ("UltRitualAnciao",         "RitualExplosivo"),
    "BencaoIntensa":           ("UltBencaoAnciao",         "BencaoIntensa"),
    "BencaoRapida":            ("UltBencaoAnciao",         "BencaoRapida"),
    "CasuloReforjado":         ("UltCasuloCristal",        "CasuloReforjado"),
    "CasuloLetal":             ("UltCasuloCristal",        "CasuloLetal"),
    "InfernoPropagado":        ("UltCorrentesInferno",     "InfernoPropagado"),
    "InfernoIntensidade":      ("UltCorrentesInferno",     "InfernoIntensidade"),
    "DrenagemTotal":           ("UltDrenagemDeVida",       "DrenagemTotal"),
    "DrenagemMassiva":         ("UltDrenagemDeVida",       "DrenagemMassiva"),
    "SonicoAmplificado":       ("UltEscudoSonico",         "SonicoAmplificado"),
    "SonicoPercussao":         ("UltEscudoSonico",         "SonicoPercussao"),
    "BestialFrenesi":          ("UltFormaBestial",         "BestialFrenesi"),
    "BestialRugidoMortal":     ("UltFormaBestial",         "BestialRugidoMortal"),
    "MagneticoSupercarregado": ("UltPulsoMagnetico",       "MagneticoSupercarregado"),
    "MagneticoCentro":         ("UltPulsoMagnetico",       "MagneticoCentro"),
    "PunicaoJulgamento":       ("UltPunicaoDivina",        "PunicaoJulgamento"),
    "PunicaoDivina2":          ("UltPunicaoDivina",        "PunicaoDivina2"),
    "DomoFortificado":         ("UltDomoRetardante",       "DomoFortificado"),
    "DomoInversor":            ("UltDomoRetardante",       "DomoInversor"),
    "DespertarFurioso":        ("UltDespertarAnciao",      "DespertarFurioso"),
    "DespertarGigante":        ("UltDespertarAnciao",      "DespertarGigante"),
}

# Current values from assets (read from grep output)
assets = {
    "AureolaExpansiva":        (22, 56),
    "AureolaFortificada":      (22, 55),
    "BarreiraCongelante":      (23, 58),
    "BarreiraExplosiva":       (39, 44),
    "BarreiraFortificada":     (39, 43),
    "BarreiraTotal":           (23, 57),
    "BencaoIntensa":           (51, 75),
    "BencaoRapida":            (51, 76),
    "BestialFrenesi":          (56, 85),
    "BestialRugidoMortal":     (56, 86),
    "CampoAmpliado":           (25, 2),
    "CasuloLetal":             (52, 78),
    "CasuloReforjado":         (52, 77),
    "ChicoteAlcance":          (32, 34),
    "ChicoteEletrico":         (32, 15),
    "ChuvaIntensa":            (26, 3),
    "CorrenteAlcance":         (36, 37),
    "CorrenteParalisante":     (36, 24),
    "CorrenteReforcada":       (36, 23),
    "CorteLetal":              (30, 12),
    "CorteTriple":             (30, 11),
    "CristaisDuplos":          (60, 59),
    "CristaisExplosivos":      (60, 60),
    "CruzDupla":               (29, 9),
    "DespertarFurioso":        (60, 93),
    "DespertarGigante":        (60, 94),
    "DomoFortificado":         (59, 91),
    "DomoInversor":            (59, 92),
    "DrenagemMassiva":         (54, 82),
    "DrenagemTotal":           (54, 81),
    "DuplaRotacao":            (32, 16),
    "EspadaAlcance":           (35, 36),
    "EspadaDuplaFantasma":     (35, 21),
    "EspadaFlamejante":        (35, 22),
    "EspelhoAmplificado":      (42, 49),
    "EspelhoExplosivo":        (42, 50),
    "EspinhosExplosivos":      (21, 54),
    "EspinhosVenenosos":       (25, 1),
    "EspinhosVenenosos2":      (21, 53),
    "Execucao":                (27, 6),
    "FugaCura":                (38, 42),
    "FugaInvulneravel":        (38, 41),
    "GarrasAlcance":           (27, 33),
    "GarrasVenenosas":         (27, 5),
    "GeloAbsoluto":            (47, 67),
    "GeloEterno":              (47, 68),
    "ImpactoSismico":          (26, 4),
    "InfernoIntensidade":      (53, 80),
    "InfernoPropagado":        (53, 79),
    "InstintoEspirito":        (41, 48),
    "InstintoFurioso":         (41, 47),
    "KarmaReforcado":          (43, 51),
    "KarmaRetribuicao":        (43, 52),
    "LaminasDuplas":           (28, 7),
    "LaminasExplosivas":       (28, 8),
    "LancaExplosiva":          (31, 14),
    "LancaPerfurante":         (31, 13),
    "LancasMultiplas":         (31, 38),
    "MagneticoCentro":         (57, 88),
    "MagneticoSupercarregado": (57, 87),
    "MeteorosDuploImpacto":    (46, 65),
    "MeteorosMaior":           (46, 66),
    "MisseisExplosivos":       (33, 18),
    "NecropoleContaminacao":   (49, 72),
    "NecropoleExercito":       (49, 71),
    "PulsoAlcance":            (34, 35),
    "PulsoCadeia":             (34, 20),
    "PulsoIntenso":            (34, 19),
    "PunicaoDivina2":          (58, 90),
    "PunicaoJulgamento":       (58, 89),
    "RaioEterno":              (44, 61),
    "RaioOvercarga":           (44, 62),
    "RitualAmpliado":          (50, 73),
    "RitualExplosivo":         (50, 74),
    "SalvaMisseis":            (33, 17),
    "SegundaChanceCura":       (37, 39),
    "SegundaChanceInvencivel": (37, 40),
    "SombrasPerfurantes":      (29, 10),
    "SonicoAmplificado":       (55, 83),
    "SonicoPercussao":         (55, 84),
    "TeiaPermanente":          (40, 46),
    "TeiaVenenosa":            (40, 45),
    "TempestadeContinua":      (45, 64),
    "TempestadeIntensa":       (45, 63),
    "VorticeDestruidor":       (48, 69),
    "VorticeExpansivo":        (48, 70),
}

print("=== VERIFICACAO COMPLETA DOS ASSETS DE EVOLUCAO ===\n")
errors = []
for fname in sorted(assets.keys()):
    cur_sa, cur_te = assets[fname]
    if fname not in expected:
        print(f"  [?] {fname}.asset - not in expected map (manual check needed)")
        continue
    exp_sa_name, exp_te_name = expected[fname]
    exp_sa = sst_rev.get(exp_sa_name)
    exp_te = set_rev.get(exp_te_name)

    sa_ok = (cur_sa == exp_sa)
    te_ok = (cur_te == exp_te)

    if sa_ok and te_ok:
        print(f"  [OK] {fname}.asset  skillAlvo={cur_sa}({specific_skill_type.get(cur_sa,'?')})  tipoEvolucao={cur_te}({skill_evolution_type.get(cur_te,'?')})")
    else:
        msg_parts = []
        if not sa_ok:
            msg_parts.append(f"skillAlvo: {cur_sa}({specific_skill_type.get(cur_sa,'?')}) -> {exp_sa}({exp_sa_name})")
        if not te_ok:
            msg_parts.append(f"tipoEvolucao: {cur_te}({skill_evolution_type.get(cur_te,'?')}) -> {exp_te}({exp_te_name})")
        print(f"  [ERR] {fname}.asset  {'; '.join(msg_parts)}")
        errors.append((fname, cur_sa, cur_te, exp_sa, exp_te))

print(f"\nTotal assets verificados: {len(assets)}")
print(f"Total com erro: {len(errors)}")
if errors:
    print("\nFIXES NEEDED:")
    for fname, cur_sa, cur_te, exp_sa, exp_te in errors:
        print(f"  {fname}: skillAlvo {cur_sa}->{exp_sa}, tipoEvolucao {cur_te}->{exp_te}")
